config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  get '/items', to: 'items#index'
  get '/items/new', to: 'items#new'
  post '/items', to: 'items#create'
  get '/items/:id', to: 'items#show'


  get "/items/:id/edit", to: "items#edit", as: "item_edit"
  patch "/items/:id/edit", to: "items_edit#update"

  post "/sessions", to: "sessions#create"
  delete '/sessions', to: 'sessions#destroy'

  get "/users/:id", to: "users#show", as: 'user'

  get :send_barter_mail, to: 'barters#send_barter_mail', as: 'send_barter_mail'

  resources :items
  resources :users
  resources :users do
    resources :items
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :items

	validates :email, :password_digest, presence: true, length: { minimum: 3 }
	validates :email, uniqueness: true
	validates :password, length: { in: 3..10 }

	def self.confirm(params)
		@user = User.find_by({email: params[:email]})
		@user.try(:authenticate, params[:password])
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		@items = Item.all;
	end

	def show
		@user = User.find_by_id(params[:id])
		@current_user = current_user
		@item = Item.find(params[:id]);
		@id = @item.user_id
		@other_user = User.find_by_id(@id)
		@email = @other_user.email
	end

	def new
		@item = Item.new;
	end

	def create
		@user = current_user
		item_params = params.require(:item).permit(:title, :price, :description, :photo)
		item_params[:user_id] = @user.id
		@item = Item.new(item_params)
		
		if @item.save
		 redirect_to('/items')
		end
	end

	

	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:email, :password)
    @user = User.confirm(user_params)
    if @user
      login(@user)
      redirect_to "/items"
    else
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  end

  def create
    userParams = params.require(:user).permit(:email, :password)
    @user = User.new userParams
    if @user.save
      login(@user)
      redirect_to "/items"
    else
      redirect_to "/"
    end
  end

  def show
    @user = current_user
    @item = Item.new
    @items = @user.items
    
  end

  def edit
    id = params[:id]
    @user = User.find_by_id(id)
  end

  def update
  end

  def destroy
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@user = User.new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/barters_helper.rb
module BartersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
      @current_user ||= User.find_by_id(session[:user_id])
    end

    def login(user)
      session[:user_id] = user.id
      @current_user = user
    end

    def logged_in?
      if current_user == nil
        redirect_to "/"
      end
    end

    def logout
      @current_user = session[:user_id] = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/index.html.erb
<%= render 'partials/nav_home' %>

<p class="shadow text2_2">eBarter</p>

<br>
<br>

<p class="script"><span>Browse below to find the right product for you!</span></p>


<div class="items_container">
	<div id="columns">
		<% @items.each do |item| %>
			<div class="items_list">
				<%= image_tag(item.photo) %>
				<!-- <img class="items_list_image" src="<%= item.photo %>"><br> -->
				<p>Title: <%= item.title %></p>
				<p>Price: $<%= item.price %></p>
				<p class="barter_tag"><a href="/items/<%= item.id %>">Barter!</a><p>
			</div>
		<% end %>
	</div>
</div>

app/views/items/new.html.erb
<%= form_for @item do |f| %>
  <span>Title: </span>
  <%= f.text_field :title, required: true %><br>
  <span>Description: </span>
  <%= f.text_field :description, required: true %><br>
  <span>Price: </span>
  <%= f.number_field :price, required: true %><br>
  <span>Photo: </span>
  <%= f.url_field :photo, required: true %><br>
  <%= f.submit %>
<% end %>

app/views/items/show.html.erb
<%= render 'partials/nav_home' %>

<div class="barter_their_half">
	<div class="their_item">
		<%= image_tag(@item.photo) %><br>
		<hr>
		<p>Title: <%= @item.title %></p>
		<p>Description: <%= @item.description %></p><br>
		<p>Price: $<%= @item.price %></p>
	</div>
</div>


<div class="barter_your_half">
	<div class="items_container2">
		<h1 class="barter_header">My Items</h1>
		<hr>
		<div class="email_div">
			<a class="email_button" target="_blank" href="mailto:<%= @email %>?subject=eBarter Request!&body=Hello there!, <%= @current_user.email %> has expressed an interest in bartering with you for your <%= @item.title %>! Please email them back if you are interested in bartering with him. Thank you!    -eBarter Team">Click Here to Email Seller!</a>
			<!-- <a class="email_button" target="_blank" href="mailto:<%= @email %>">Click Here to Contact Seller!</a> -->
		</div>
		<hr>
		<div id="columns2">
			<% @current_user.items.each do |item| %>
				<div class="items_list2">
					<%= image_tag(item.photo, class: "items_list_image2") %><br>
					<p>Title: <%= item.title %></p>
					<p>Price: $<%= item.price %></p>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>eBarter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="icon" href="http://www.rongfa.biz/assets/templates/main/images/icon-7.png">
</head>
<body>

<!-- <a href="/items/new">Make a New Record</a><br> -->

<%= yield %>

</body>
</html>

app/views/partials/_login.erb
<div id="login-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Login</h4>
      </div>
      <div class="modal-body">
      	<div class="signup-wrapper">
      		 <%= form_for @user, url: sessions_path, method: 'post' do |f| %>
          <div>
            <%= f.email_field :email, placeholder: 'Email' %>
            <%= f.password_field :password, placeholder: 'Password' %>
            <%= f.submit 'Sign In' %>

          </div> 
          <% end %>
      	</div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/partials/_nav_home.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <ul class="home_brand">
        <a class="navbar-brand" href="/">Home</a>
      </ul>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav home_nav_button navbar-right">
        <% if current_user %>
          <li><%= link_to "Logout", sessions_path , {method: :delete} %></li>
          <li><%= link_to "Profile", user_path(current_user)%></li>
          <li><%= link_to "Items", "/items" %></li>
        <% else %>
          <li><a data-toggle="modal" href="#signup-modal">Sign Up</a></li>
          <li><a data-toggle="modal" href="#login-modal">Login</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/partials/_new_item.erb
<div id="item-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">New Item</h4>
      </div>
      <div class="modal-body">
        <div class="signup-wrapper">
           <%= form_for @item do |f| %>
             <span>Title: </span>
             <%= f.text_field :title, required: true %><br>
             <span>Description: </span>
             <%= f.text_field :description, required: true %><br>
             <span>Price: </span>
             <%= f.number_field :price, required: true %><br>
             <span>Photo: </span>
             <%= f.url_field :photo, required: true %><br>
             <%= f.submit %>
          <% end %>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/partials/_signup.erb
<div id="signup-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Sign-Up</h4>
      </div>
      <div class="modal-body">
        <div class="signup-wrapper">
           <%= form_for @user do |f| %>
        <%= f.email_field :email, class: "new-user-form", placeholder: 'email123@domain.com' %>
        <%= f.password_field :password, class: "new-user-form", placeholder: 'password' %>
        <%= f.submit 'Sign Up', id: "signup-button", class: 'btn btn-default text-center'%>
        <% end %>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/partials/_user_nav.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <ul class="home_brand">
        <a class="navbar-brand" href="/">Home</a>
      </ul>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav home_nav_button navbar-right">
        <li><%= link_to "Logout", sessions_path , {method: :delete} %></li>
        <li><a data-toggle="modal" href="#item-modal">New Item</a></li>
        <li><%= link_to "Items", "/items" %></li>

      </ul>
    </div>
  </div>
</nav>

app/views/users/show.html.erb
<%= render 'partials/user_nav' %>

<!-- new item modal -->
<div id="item-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">New Item</h4>
      </div>
      <div class="modal-body">
        <div class="signup-wrapper">
           <%= form_for @item do |f| %>
             <span>Title: </span>
             <%= f.text_field :title, required: true %><br>
             <span>Description: </span>
             <%= f.text_field :description, required: true %><br>
             <span>Price: </span>
             <%= f.number_field :price, required: true %><br>
             <span>Photo: </span>
             <%= f.url_field :photo, required: true %><br>
             <%= f.submit %>
          <% end %>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<br>
<br>

<!-- listing user's items -->
<p class="profile_header script"><span>Welcome back <%= @user.email %>! You have <%= @user.items.length %> items listed!</span></p>

<div class="items_container">
  <div id="columns">
    <% @items.each do |item| %>
      <div class="items_list">
        <%= image_tag(item.photo, class: "items_list_image") %><br>
        <p>Title: <%= item.title %></p>
        <p>Description: <%= item.description.first(80) %>...</p>
        <p>Price: <%= item.price %></p>
        <a href="/items/<%= item.id %>">Read More!</a>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<%= render 'partials/nav_home' %>
<%= render 'partials/login' %>
<%= render 'partials/signup' %>

<head>
	<link href='https://fonts.googleapis.com/css?family=Arvo:700' rel='stylesheet' type='text/css'>
</head>
<div class="plate">
  <p class="script"><span>Welcome</span></p>
  <p class="shadow text1">TO THE</p>
  <p class="shadow text2">eBarter</p>
  <p class="shadow text3">WEBSITE</p>
  <br>
  <p class="script"><span>by Tom Rehnert</span></p>
</div>